name: gobgc
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.9   # Python version 3.9 or newer
    - dask          # Parallel processing library
    - distributed
    - h5py          # Wrapper for HDF5
    - jupyter       # Jupyter architecture
    - jupyterlab    # Jupyter Lab environment
    - nb_conda_kernels #
    - matplotlib    # 2D plotting library
    - cmocean
    - netcdf4       # Wrapper for netcdf4
    - erddapy
    - pandas>=2.0        # Labeled array library
    - seaborn       # Statistical visualizations
    - cartopy
    - xarray        # N-d labeled array library
    - gsw           # TEOS Gibbs Seawater properties
    - zarr
    - tqdm
    - pyarrow
    - ipywidgets
    - pip
    - pip:
      - pip install argopy==0.1.14rc2

